---
title: "stl leads inequity"
format: html
execute: 
  warning: false
---

```{r}
library(tidyverse)
library(janitor)
library(here)
```

```{r}
stl_lead <- read_csv(here::here('data', 'stl_lead.csv')) %>% 
  clean_names()


```

```{r}
stl_lead_prop <- data.frame(stl_lead) %>% 
  mutate(prop_white = (white/total_pop) * 100)
```

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(y = pct_elevated, x = prop_white)) + geom_jitter(aes(alpha = .5, size = 5, opacity = .5, color = prop_white)) +
  scale_color_gradient(low = "green", high = "blue") + labs(title = 'yo')

stl_lead_plot
```

```{r}
ggsave(here::here('figs', 'stl_lead_plot.png'), height = 5, width = 6) 
```

We see that children have higher elevated blood live in areas with lower proportion of white people, while children that live in higher white population proportions have less elevated blood

## histogram

```{r}

stl_plot_df <- data.frame(stl_lead_prop)
ggplot(data = stl_plot_df, aes(x = pct_elevated)) + geom_histogram(aes(fill = 'blue'))
```
